client:
	g++ -o remoteClient inet_str_client.cpp
	./remoteClient -p 9002 -i localhost -d lala

client2:
	g++ -o remoteClient inet_str_client.cpp
	./remoteClient -p 9002 -i localhost -d test

run_client:
	./remoteClient 127.0.1.1 9002